### ISSUE TITLE
Minor typo: string "conversation" should be "conversion"

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [Pungyeon/clean-go-article#22]
![image](https://user-images.githubusercontent.com/19352442/60439988-d0878500-9be1-11e9-8e34-e7449efd5a96.png)

Minor typo that I missed when reviewing the doc :) It's funny, I actually make this typo myself quite a lot 😄 The brain works in interesting ways.

I figured I'd just make an issue for it instead of doing a full-fledged PR. Thanks!

**Comment by Pungyeon** [comment]
Good catch! 😄 Yeah, no need to make a PR...

**Comment by Pungyeon** [comment]
@AleksandrHovhannisyan I have invited you to be a collaborator, so that you have push access to the repository. You've done so much work on this repo and I thought it would be so much easier for you to just push these kind of small fixes in the future, as well as help review my future additions to the article.

**Comment by AleksandrHovhannisyan** [comment]
@Pungyeon Sounds great!
